### ISSUE TITLE
Non jquery version on iOS

### ISSUE THREAD

**Issue by tbnobody** [wieringen/tinycolorpicker#12]
It seams that the non-jquery version is not working in safari on iOS (9).
Is this a bug or a feature? The color chooser is opening and closing when I touch the image but the choosen color is not applied.

**Comment by tbnobody** [comment]
If I replace 
```javascript
_getColorCanvas(event.originalEvent.touches[0]);
```
with 
```javascript
_getColorCanvas(event.touches[0]);
```
it works on iOS. 
I just cannot test it on other touch devices.

**Comment by wieringen** [comment]
You are right. I added your fix in the latest version.
