### ISSUE TITLE
Uncaught SecurityError in demo

### ISSUE THREAD

**Issue by xoorath** [wieringen/tinycolorpicker#8]
Hey,

Downloaded the zip from `http://baijs.com/tinycolorpicker/` and running the demos doesn't seem to work. Opening simple/index.html will open and show the color picker normally but selecting a color does not work. The console will output:

```
Uncaught SecurityError: Failed to execute 'getImageData' on 'CanvasRenderingContext2D': The canvas has been tainted by cross-origin data.jquery.tinycolorpicker.js:223 _getColorCanvasjquery.tinycolorpicker.js:153 (anonymous function)jquery-latest.min.js:3 m.event.dispatchjquery-latest.min.js:3 r.handle
```

edit:
On windows running chrome.

**Comment by TravelingTechGuy** [comment]
+1

**Comment by gcs278** [comment]
Same over here

**Comment by antoniosg88** [comment]
Happened the same for me, I solved on my local environment and I just commit the fix here: 
https://github.com/wieringen/tinycolorpicker/commit/84d29d1c5a04985c1f2acb5007ab5ce94deaa978

I created a pull request for this.
